#!/usr/bin/env python3
"""Generate the fixed-point world projection lookup table."""

import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_PATH = os.path.join(ROOT, "src", "engine", "world_proj_lut.c")

# MUST match WORLD_Z_NEAR / WORLD_Z_FAR in src/engine/world.h.
Z_NEAR = 256
Z_FAR = 4096
VALUES_PER_LINE = 16


def value(z):
    if z < Z_NEAR:
        z = Z_NEAR
    return (Z_NEAR << 8) // z


def main():
    values = [value(z) for z in range(Z_FAR + 1)]

    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(
            "/* AUTO-GENERATED by tools/gen_proj_lut.py; do not edit;\n"
            " * regenerate with tools/gen_proj_lut.py if Z_NEAR/Z_FAR change.\n"
            " */\n\n"
        )
        f.write('#include "world.h"\n\n')
        f.write(f"#define WORLD_PROJ_LUT_COUNT {Z_FAR + 1}\n\n")
        f.write(
            "_Static_assert(WORLD_PROJ_LUT_COUNT == (WORLD_Z_FAR + 1),\n"
            '    "world_proj_lut.c out of date: regenerate with tools/gen_proj_lut.py");\n\n'
        )
        f.write("const u16 WORLD_projLUT[WORLD_PROJ_LUT_COUNT] =\n{\n")
        for i in range(0, len(values), VALUES_PER_LINE):
            chunk = values[i:i + VALUES_PER_LINE]
            f.write("    " + ", ".join(str(v) for v in chunk))
            if i + VALUES_PER_LINE < len(values):
                f.write(",")
            f.write("\n")
        f.write("};\n")

    print(f"wrote {os.path.relpath(OUT_PATH, ROOT)}: {len(values)} entries")


if __name__ == "__main__":
    main()
